version: "3.9"
services:
  node_app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jacobo
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db_data:/data/db


volumes:
  db_data:
    driver: local
    
